In [16]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import spacy

In [17]:
df = pd.read_json('condensed_2018.json')

print (df.shape)
df.head()

(3510, 8)

,source,id_str,text,created_at,retweet_count,in_reply_to_user_id_str,favorite_count,is_retweet
0,Twitter for iPhone,1079888205351145472,HAPPY NEW YEAR! https://t.co/bHoPDPQ7G6,2018-12-31 23:53:06+00:00,33548,NaN,136012,False
1,Twitter for iPhone,1079830268708556800,"....Senator Schumer, more than a year longer t...",2018-12-31 20:02:52+00:00,17456,25073877.0,65069,False
2,Twitter for iPhone,1079830267274108928,Heads of countries are calling wanting to know...,2018-12-31 20:02:52+00:00,21030,NaN,76721,False
3,Twitter for iPhone,1079763923845419008,It’s incredible how Democrats can all use thei...,2018-12-31 15:39:15+00:00,29610,NaN,127485,False
4,Twitter for iPhone,1079763419908243456,"I’m in the Oval Office. Democrats, come back f...",2018-12-31 15:37:14+00:00,30957,NaN,132439,False

In [22]:
nlp = spacy.load('en')

df['doc'] = [nlp(text) for text in df.text]
df.head()

,source,id_str,text,created_at,retweet_count,in_reply_to_user_id_str,favorite_count,is_retweet,tokens,num_tokens,doc
0,Twitter for iPhone,1079888205351145472,HAPPY NEW YEAR! https://t.co/bHoPDPQ7G6,2018-12-31 23:53:06+00:00,33548,NaN,136012,False,"(HAPPY, NEW, YEAR, !, https://t.co/bHoPDPQ7G6)",5,"(HAPPY, NEW, YEAR, !, https://t.co/bHoPDPQ7G6)"
1,Twitter for iPhone,1079830268708556800,"....Senator Schumer, more than a year longer t...",2018-12-31 20:02:52+00:00,17456,25073877.0,65069,False,"(...., Senator, Schumer, ,, more, than, a, yea...",44,"(...., Senator, Schumer, ,, more, than, a, yea..."
2,Twitter for iPhone,1079830267274108928,Heads of countries are calling wanting to know...,2018-12-31 20:02:52+00:00,21030,NaN,76721,False,"(Heads, of, countries, are, calling, wanting, ...",45,"(Heads, of, countries, are, calling, wanting, ..."
3,Twitter for iPhone,1079763923845419008,It’s incredible how Democrats can all use thei...,2018-12-31 15:39:15+00:00,29610,NaN,127485,False,"(It, ’s, incredible, how, Democrats, can, all,...",63,"(It, ’s, incredible, how, Democrats, can, all,..."
4,Twitter for iPhone,1079763419908243456,"I’m in the Oval Office. Democrats, come back f...",2018-12-31 15:37:14+00:00,30957,NaN,132439,False,"(I, ’m, in, the, Oval, Office, ., Democrats, ,...",55,"(I, ’m, in, the, Oval, Office, ., Democrats, ,..."

In [21]:
# Function to lemmatize docs
# source: 
# https://github.com/dipanjanS/practical-machine-learning-with-python/
# blob/master/notebooks/Ch07_Analyzing_Movie_Reviews_Sentiment/Text%20Normalization%20Demo.ipynb

def lemmatize_text(text):
    text = nlp(text)
    text = ' '.join([word.lemma_ if word.lemma_ != '-PRON-' else word.text for word in text])
    return text